### ISSUE TITLE
LumixEngine not compiling

### ISSUE THREAD

**Issue by jairbubbles** [liamkf/msfastbuild#4] opened 2016-09-14 09:58 UTC
I'm testing with some random projects. https://github.com/nem0/LumixEngine

I have an error at the end of the compilation:

```
1> Run: C:\Users\Julien\Desktop\LumixEngine-master\projects\tmp\vs2015\studio_postbuild.bat.txt
FBuild: OK: all
Time: 0.837s
Building physics
No workers available - Distributed compilation disabled
Alias: all
Failed due to missing file: C:\Users\Julien\Desktop\LumixEngine-master\projects\tmp\vs2015\postbuild
FBuild: Error: BUILD FAILED: all
Time: 0.523s
4/12 built.
```

**Comment by liamkf** [comment] 2016-09-15 01:38
That was me being silly, fixed in the next revision! :)

**Comment by jairbubbles** [comment] 2016-09-15 06:27
It's indeed compiling now.
But if I press F5 with the studio project selected. I got asked to compile outdated projects.
If I press Yes here is the log:
[log.txt](https://github.com/liamkf/msfastbuild/files/473953/log.txt)

**Comment by liamkf** [comment] 2016-09-15 14:14
Yes that's somewhat intentional, I don't mess with the msbuild status files so that both can still work as intended. I believe Incredibuild and the snvsi (which are the only 'build interceptors' I've used) do the same.

**Comment by jairbubbles** [comment] 2016-09-15 15:07
Ok but I guess you should have a copmmand "Launch (FastBuild)" then.

**Comment by liamkf** [comment] 2016-09-16 19:15
Seems like a reasonable feature request... Incredibuild does have that button, but I've never used it! :)

**Closed as completed** 2016-09-17 03:20 UTC
Labels: bug
